# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bb33389fa62e7ad35767804e2e610c53b8d5acf07a18e6c9a28a995180369936792cb3340bb24795e8cf128e839b84011d3688ea198c7fc0b4b54b0e3202748d

test:
  secret_key_base: d6dda88de8525030ee4cbe40eee84e560da834bc498af134236c253fa843826ba39b462ad744710b68bc43515f6b90219347e64e963180639bf446cf96c1e6d3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
